### ISSUE TITLE
build and run requirements for conda package are identical

### ISSUE THREAD

**Issue by tngTUDOR** [polca/premise#8]
Currently, the requirements to build the coda package, for running and testing are the same.

```yaml
requirements:
  build:
    - python
    - wurst
    - numpy
    - pandas
    - bw2io
    - bw2data
    - xarray <=0.13.0
    - pytest
    - pytest-cov
    - coveralls
    - setuptools
  run:
    - python
    - wurst
    - numpy
    - pandas
    - bw2io
    - bw2data
    - xarray <=0.13.0
    - pytest
    - pytest-cov
    - coveralls
```

I suggest you remove the "testing" packages for the running environment, this would prevent conda from installing `pytest` for example when all you want is to run rmnd-lca, and trust that the tests are "passing".
